# Generated by Django 2.2 on 2019-12-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20191215_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='course_id',
            new_name='Course_or_Org_id',
        ),
    ]
