# Generated by Django 2.2 on 2019-10-14 23:04

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190921_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercourse',
            options={'verbose_name': '輪播課程', 'verbose_name_plural': '輪播課程'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '課程信息', 'verbose_name_plural': '課程信息'},
        ),
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': '課程資源', 'verbose_name_plural': '課程資源'},
        ),
        migrations.AlterModelOptions(
            name='coursetag',
            options={'verbose_name': '課程標簽', 'verbose_name_plural': '課程標簽'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '課程章節', 'verbose_name_plural': '課程章節'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '視頻', 'verbose_name_plural': '視頻'},
        ),
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='後端開發', max_length=20, verbose_name='課程類別'),
        ),
        migrations.AlterField(
            model_name='course',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='點擊數'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='課程機構'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '初級'), ('zj', '中級'), ('gj', '高級')], max_length=2, verbose_name='難度'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='課程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='課程詳情'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏人數'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(max_length=1000, verbose_name='訪問地址'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否廣告位'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_classics',
            field=models.BooleanField(default=False, verbose_name='是否經典'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='學習時長（分鐘）'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='課程名'),
        ),
        migrations.AlterField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=300, verbose_name='課程公告'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0, verbose_name='學習人數'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=10, verbose_name='課程標簽'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='講師'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='教師提示'),
        ),
        migrations.AlterField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='課程須知'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file',
            field=models.FileField(max_length=200, upload_to='course/resourse/%Y/%m', verbose_name='下載地址'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='標簽'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='學習時長（分鐘數）'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='章節名'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加時間'),
        ),
        migrations.AlterField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='學習時長(分鐘數)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章節'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, verbose_name='視頻名'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=1000, verbose_name='訪問地址'),
        ),
    ]
