# Generated by Django 2.2 on 2019-10-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20191014_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='course',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learn_times',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_tell',
        ),
        migrations.RemoveField(
            model_name='course',
            name='youneed_know',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(max_length=1000, verbose_name='封面圖'),
        ),
    ]
