# Generated by Django 2.2 on 2019-10-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20191014_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseResource',
        ),
    ]
