# Generated by Django 2.2 on 2019-10-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20191015_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=500, verbose_name='課程描述'),
        ),
    ]
