# Generated by Django 2.2 on 2019-10-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20191015_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=1000, verbose_name='課程描述'),
        ),
    ]
