# Generated by Django 2.2 on 2019-10-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20191015_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=2000, verbose_name='課程描述'),
        ),
    ]
