# Generated by Django 2.2 on 2019-10-19 00:28

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notice',
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='課程詳情'),
        ),
    ]
