# Generated by Django 2.2 on 2019-10-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=10, verbose_name='課程標簽'),
        ),
    ]
