# Generated by Django 2.2 on 2019-10-19 15:43

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='課程詳情'),
        ),
    ]
