# Generated by Django 2.2 on 2019-10-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
