# Generated by Django 2.2 on 2019-10-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_course_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
    ]
