# Generated by Django 2.2 on 2019-10-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_course_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
    ]
