# Generated by Django 2.2 on 2019-10-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20191014_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='category',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='city',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='tag',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
