# Generated by Django 2.2 on 2019-10-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20191014_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='address',
        ),
    ]
