# Generated by Django 2.2 on 2019-10-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_courseorg_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='points',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_company',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_position',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_years',
        ),
    ]
