# Generated by Django 2.2 on 2019-10-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_teacher'),
        ('organizations', '0009_remove_courseorg_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
