# Generated by Django 2.2 on 2019-10-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='students',
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='學習人數'),
        ),
    ]
