# Generated by Django 2.2 on 2019-10-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20191019_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='學習人數'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='點擊數'),
        ),
    ]
