# Generated by Django 2.2 on 2019-10-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20191019_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.CharField(max_length=1000, verbose_name='封面圖'),
        ),
    ]
